spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdata
    username: postgres
    password: password

logging:
  level:
    org.springframework.data.r2dbc: Debug
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
    version: openapi_3_0
